# Generated by Django 2.2.5 on 2022-03-09 00:46

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('manufacturer', models.CharField(max_length=100)),
                ('modelname', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 3, 9, 0, 46, 39, 99346))),
            ],
        ),
    ]
